---
title: "04_deconvolution_revision"
author: "Daniel Schulz"
date: "2026-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

library(ggpubr)
library(SingleCellExperiment)
library(survivalAnalysis)
library(ggsurvfit)
library(survminer)
library(survival)
library(edgeR)
library(cowplot)
library(ggrepel)
library(igraph)
library(ggraph)
library(ggrepel)
library(scales)
library(ggnewscale)
```

```{r}
mount_path <- "/mnt/immucan_volume/processed_data/NSCLC2_cohort/"
out_folder <- "/mnt/immucan_volume/processed_data/NSCLC2_cohort/Figures/Figure_3_supp/"

if (!dir.exists(out_folder)) {
  dir.create(out_folder)
}
```

# load data
we will load the data we generated at the beginning of figure 2
```{r}
dat <- readRDS(paste0(mount_path,"Figures/scores_for_sharing/abundances_dat.rds"))
dens_dat <- readRDS(paste0(mount_path,"Figures/scores_for_sharing/densities_dat.rds"))
cello_dat <- readRDS(paste0(mount_path,"Figures/scores_for_sharing/cello_dat.rds"))
clin_dat <- read.csv("/mnt/immucan_volume/clinical_data/Lung_NSCLC2/20230825/NSCLC2_for_R_update_2024.csv")
traits <- read_csv(paste0(mount_path,"Figures/scores_for_sharing/all_traits.csv"))


# variables
data_type <- unique(str_split_i(string = colnames(dat[,-1]),pattern = "__",i = 2))
```

# deconvolution of RNAseq
```{r, fig.width=25, fig.height=8}
dat <- read.csv("/mnt/immucan_volume/processed_data/NSCLC2_cohort/data/RNASeq/Rout/tables/RNAseq/xcell_results/xCell_TPM_norm_for_xCell_xCell_1129103125.txt", sep = "\t")
dat_t <- as.data.frame(t(dat[,-1]))
colnames(dat_t) <- dat$X
dat_t$immucan_id <- gsub("\\.","-",rownames(dat_t))
rownames(dat_t) <- NULL
unique(dat_t$immucan_id)
dat_t
dat <- left_join(dat_t,clin_dat[,c("immucan_id","simple_stage", "simple_histology")],"immucan_id")

dim(dat)


sigs <- dat_t %>%
  pivot_longer(-immucan_id) %>%
  left_join(clin_dat[,c("immucan_id","simple_stage", "simple_histology")],by = "immucan_id") %>%
  filter(simple_histology == "Adenocarcinoma") %>%
  select(immucan_id,name, value,simple_stage) %>%
  mutate(stage = ifelse(simple_stage == "I",1,NA),
         stage = ifelse(simple_stage == "II",2,stage),
         stage = ifelse(simple_stage == "III",3,stage),
         stage = ifelse(simple_stage == "IV",4,stage),
         stage = as.numeric(as.factor(stage))) %>%
  filter(stage != 4) %>%
  group_by(name) %>%
  nest() %>%
  mutate(model = map(data, ~ lm(value ~ stage, data = .x)),
         summary = map(model, broom::tidy)) %>%
  select(name, summary) %>%
  unnest(c(summary)) %>%
  filter(term == "stage") %>%
  mutate(tech = str_split_i(name,"__",2)) %>%
  group_by(tech) %>%
  mutate(FDR = p.adjust(p = p.value,method = "BH"),
         sig_p = ifelse(p.value < 0.05,TRUE, FALSE),
         sig_fdr = ifelse(FDR < 0.1,TRUE, FALSE))

summary_dat <- sigs %>%
  filter(sig_p == TRUE) %>%
  #filter(grepl("CD8_GATA3_BCL2|^CD8_density|CD8_Ki67_density|CD8_TCF7_density|Tumor_IDO1",name)) %>%
  mutate(y_position = 1000) %>%
  ungroup() %>%
  as.data.frame()

p2 <- dat_t %>%
  pivot_longer(-immucan_id) %>%
  mutate(tech = str_split_i(name,"__",2)) %>%
  left_join(clin_dat,"immucan_id") %>%
  filter(simple_histology == "Adenocarcinoma") %>%
  select(immucan_id,name, value,simple_stage, tech) %>%
  mutate(stage = ifelse(simple_stage == "I",1,NA),
         stage = ifelse(simple_stage == "II",2,stage),
         stage = ifelse(simple_stage == "III",3,stage),
         stage = ifelse(simple_stage == "IV",4,stage),
         stage = as.numeric(as.factor(stage)),
         name = gsub(pattern = "density_",replacement = "",x = name)) %>%
  filter(#name %in% summary_dat$name,
         stage != 4) %>%
  ggplot(aes(x = name,y = log10(value+1),fill=as.factor(stage))) +
  geom_boxplot(outliers = FALSE)+
  geom_jitter(aes(col = as.factor(stage)),position = position_jitterdodge(jitter.width = 0.2),size= 0.5)+
  scale_fill_manual(values = alpha(c("1" = "palevioletred3", "2" = "darkseagreen3", "3" = "dodgerblue"),alpha = 0.6))+
  scale_color_manual(values = c("1" = "palevioletred3", "2" = "darkseagreen3", "3" = "dodgerblue"))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90,vjust= 0.5, hjust = 1),
        axis.title = element_blank())+
  guides(fill=guide_legend(title="Stage"),
         col=guide_legend(title="Stage"))+
  geom_text(data = summary_dat, aes(x = name,y=1,label = paste0("fdr: ",sig_fdr)), inherit.aes = FALSE)+
  geom_text(data = summary_dat, aes(x = name,y=1,label = paste0("p : ",round(p.value,digits = 3))), inherit.aes = FALSE)+
  ggtitle(label = "LUAD")
  
p2

dat_t %>%
  pivot_longer(-immucan_id) %>%
  mutate(tech = str_split_i(name,"__",2)) %>%
  left_join(clin_dat,"immucan_id") %>%
  filter(simple_histology == "Adenocarcinoma") %>%
  distinct(immucan_id)


```

```{r}
traits$RNA <- traits$immucan_id %in% dat_t$immucan_id

cur_traits <- traits %>% 
  filter(simple_histology == "Adenocarcinoma")

table(cur_traits$stage,cur_traits$RNA)
```

