---
title: "broad cellohood clusters"
author: "Daniel Schulz"
date: "2026-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(SingleCellExperiment)
```



```{r}
mount_path <- "/mnt/immucan_volume/processed_data/NSCLC2_cohort/"
```

# cello hood Panel 1 - PC1
we will also read this in from the old location
```{r}
df <- read.csv("/mnt/immucan_volume/processed_data/NSCLC2_cohort/Figures/scores_for_sharing/NSCLC2_for_daniel.csv")

sce1 <- readRDS(paste0(mount_path,"data/IMC/Panel_1/Rout/sce.rds"))


head(df)
df <- df %>%
  mutate(cell_id = paste0(SampleId,"_",ROI,"_",ObjectNumber))
cluster <- df$X0.5.13
names(cluster) <- df$cell_id

sum(names(cluster) %in% sce1$cell_id)

sce1$broad_cellohood <- cluster[sce1$cell_id]
sce1$broad_cellohood <- paste0("CN_",sce1$broad_cellohood)
# remove some unwanted columns in sce
sce1$Study <- NULL
sce1$Indication <- NULL
sce1$ROIonSlide <- NULL
sce1$Pooled <- NULL
sce1$Sample.Type <- NULL
sce1$Position <- NULL
sce1$ROI_position <- NULL

saveRDS(sce1,paste0(mount_path,"data/IMC/Panel_1/Rout/sce.rds"))

# update coldata object
p1 <- as.data.frame(colData(sce1))
rownames(p1) <- NULL
p1 <- p1 %>%
  filter(ROI != 4)
```

```{r, fig.height=10, fig.width=14}
library(ComplexHeatmap)
library(viridis)
library(circlize)
cur_sce <- sce1[,sce1$ROI != 4]

# fraction data
cur_dat <- as.data.frame(colData(cur_sce))

frac_dat <- cur_dat %>%
  group_by(broad_cellohood,.drop = FALSE) %>%
  dplyr::count(celltypes) %>%
  mutate(total_cells = sum(n),
         CN_freq = round(n/total_cells, digits = 2)*100) %>%
  pivot_wider(id_cols = broad_cellohood,names_from = celltypes, values_from = CN_freq, values_fill = 0) %>%
  ungroup() %>%
  as.data.frame()

# generate data to merge with expression data which we can filter exp on later
merge_info <- frac_dat %>%
  pivot_longer(cols = -broad_cellohood,names_to = "celltypes")

# generate matrix for heatmap
rownames(frac_dat) <- frac_dat$broad_cellohood
frac_dat <- t(frac_dat[,-1])


# expression data
cur_dat <- as.data.frame(t(assay(cur_sce, "exprs")))
cur_dat$broad_cellohood <- cur_sce$broad_cellohood
cur_dat$celltypes <- cur_sce$celltypes
head(cur_dat)

cur_dat <- cur_dat %>%
  pivot_longer(-c(celltypes,broad_cellohood)) %>%
  group_by(celltypes, broad_cellohood,name,.drop = FALSE) %>%
  summarise(mean_exp = mean(value))

# merge with fraction data and filter only those expression that the respective cell type is present with at least 2% in the cluster
cur_dat <- cur_dat %>%
  left_join(merge_info,by = c("broad_cellohood", "celltypes")) %>%
  filter(value > 2)


# fractions to merge
exp_dat <- cur_dat %>%
  mutate(type = paste0(celltypes,": ", name)) %>%
  filter(type %in% c("B: CD40", "B: CD20","CD4: LAG3", "CD8: PD1","CD8: GrzB", "CD8: LAG3", "CD8: Ki67", "CD8: TCF7","MacCD163: Ido1","MacCD163: PDL1","MacCD163: CD14","MacCD163: CD68",
                     "MacCD163: CD206","Mura: SMA","Tumor: cleavedPARP","Tumor: Ecad","Tumor: HLADR","Tumor: CD15","Tumor: CarbonicAnhydrase",
                     "Tumor: PDL1","Tumor: Ki67","Tumor: B2M")) %>%
  pivot_wider(id_cols = broad_cellohood,names_from = type, values_from = mean_exp) %>%
  as.data.frame()
rownames(exp_dat) <- exp_dat$broad_cellohood
exp_dat <- exp_dat[,-1]
exp_dat_scaled <- t(scale(exp_dat))

# match column names of both matrices
exp_dat_scaled <- exp_dat_scaled[,colnames(frac_dat)]
# generate complex heatmap

#color functions
expression_col_fun <- colorRamp2(
  c(-3, 0, 3), 
  c("blue", "white", "red")
)
fraction_col_fun <- colorRamp2(seq(0, 50, length.out = 50), viridis(50))

# clustering 
col_clustering <- hclust(dist(t(frac_dat)))

ht1 <- Heatmap(
  frac_dat,
  name = "Fraction",
  col = fraction_col_fun,
  cluster_rows = TRUE,
  cluster_columns = col_clustering,
  show_row_names = TRUE,
  show_column_names = TRUE,
  rect_gp = gpar(col = "white", lwd = 1),
  cell_fun = function(j, i, x, y, width, height, fill) {
    value <- frac_dat[i, j]
    fill_col <- fraction_col_fun(value)  # get fill color from scale
    rgb_col <- col2rgb(fill_col) / 255   # normalize RGB
    lum <- 0.299 * rgb_col[1] + 0.587 * rgb_col[2] + 0.114 * rgb_col[3]  # luminance

    text_col <- if (lum < 0.5) "white" else "black"

    grid.text(
      label = round(value),
      x = x, y = y,
      gp = gpar(fontsize = 8, col = text_col)
    )
  }
)

anno_dat <- as.data.frame(table(cur_sce$broad_cellohood))
colnames(anno_dat) <- c("broad_cellohood","ncells")

ht2 <- Heatmap(
  exp_dat_scaled,
  name = "Z-scored\nExpression",
  rect_gp = gpar(col = "white", lwd = 1),
  col = expression_col_fun,
  top_annotation = columnAnnotation(n_cells = anno_barplot((anno_dat$ncells))),
  
  cluster_rows = FALSE,  # Already clustered by ht1
  cluster_columns = col_clustering,
  show_row_names = TRUE,  # Avoid duplication
  show_column_names = TRUE,
  heatmap_legend_param = list(
    at = c(-3,-2,-1, 0, 1,2,3),  # control tick marks
    color_bar = "continuous"
  )
)

#pdf(paste0(out_folder,"Fig_1F_broad_cellohood_heatmap.pdf"),
#    width = 12,
#    height = 8)
ht2 %v% ht1
#dev.off()
```
